### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ElPumpo** [Drakensin/Dungeons-and-Delving#3]
# TODO
- [ ] decide name for the java mod
    - [ ] release it on github
- [ ] move distro to a organization
- [ ] sound assets
    - [ ] `alertSound`
    - [ ] `attackSound`
    - [ ] `dieSound`
    - [ ] `hurtSound`
    - [ ] `idleSound`
    - [ ] various `dropSound`, picking up and dropping items
- [ ] balance items
    - [ ] balance monsters and other creatures
- [ ] work on dungeon overhaul
